# SITE CONFIGURATION
baseurl: ""
url: "https://akhila-ashokan.github.io/"

# THEME-SPECIFIC CONFIGURATION
title: Akhila Ashokan                                   # site's title
description: "My professional website"                  # used by search engines
# avatar: assets/img/triangle.png                         # Empty for no avatar in navbar
# favicon: assets/favicon.ico                             # Icon displayed in the tab

# Header and footer text
header_text: Welcome to my professional webpage!  # Change Blog header text
header_feature_image: assets/img/pexels/book-coffee.webp

# theme: jekyll-theme-cayman
remote_theme: sylhare/Type-on-Strap 



